# A single-node HBase and Zookeeper cluster with persistent, local storage.
# Prometheus metrics are exported from the Zookeeper server, HBase Master, and HBase Regionserver.
# See port mappings for more details.

version: '3.7'
services:

  hbase:
    image: mckdev/hbase:nightly
    hostname: hbase
    build: .
    volumes:
      - $PWD/hbase-data:/data
      - $PWD/hbase-site.xml:/opt/hbase/conf/hbase-site.xml
    ports:
      - 8080:8080   # REST API
      - 9090:9090   # Thrift API
      - 16000:16000 # Master API
      - 16010:16010 # Master UI
      - 16020:16020 # Regionserver API
      - 16030:16030 # Regionserver UI