#!/bin/bash

set -ex

cd $(dirname $0)

if [[ "$DOCKER_TAG" = "nightly" ]]
then
  # if we're bulding the 'nightly' image tag, we need to build from the HBase repo's HEAD
  REF="master"
elif [[ "$DOCKER_TAG" ~= '^[0-9.]+$' ]]
  # if we're building a release version, we need to add the 'rel/' prefix to the HBase repo ref
  REF="rel/$DOCKER_TAG"
else
  # otherwise, the image tag matches the ref
  REF="$DOCKER_TAG"
fi

docker build ../.. \
  --file $DOCKERFILE_PATH \
  --tag $IMAGE_NAME \
  --build-arg HBASE_REF="$REF"