#!/bin/bash

##
# overrides the 'push' phase of Docker Hub automated builds
##

set -ex

# push whatever was just built
docker push $DOCKER_REPO:$DOCKER_TAG

# add 'latest' tag if this build wasn't the HBase HEAD
if ! [[ "$DOCKER_TAG" = 'latest-snapshot' ]]
then
    docker tag $DOCKER_REPO:$DOCKER_TAG $DOCKER_REPO:latest
    docker push $DOCKER_REPO:latest
fi