name: Docker Image CI

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}  
    - name: Extract git tag (hbase ref) from full ref
      uses: olegtarasov/get-tag@v2.1
      id: tagName
    - name: Extract container image tag from hbase ref
      id: extractImageTag
      run: echo "::set-output name=tag::${GIT_TAG_NAME#rel/}"
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg HBASE_REF=$GIT_TAG_NAME --tag mckdev/hbase:${steps.extractImageTag.outputs.tag} --tag mckdev/hbase:latest
    - name: Push the container image to Docker Hub
      run: docker push mckdev/hbase:${steps.extractImageTag.outputs.tag} mckdev/hbase:latest
